# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cortex.integration.grpc import cortex_pb2 as cortex__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortex_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CortexCertificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Certify = channel.unary_unary(
                '/cortex.CortexCertification/Certify',
                request_serializer=cortex__pb2.CertifyRequest.SerializeToString,
                response_deserializer=cortex__pb2.CertifyResponse.FromString,
                _registered_method=True)
        self.GetContext = channel.unary_unary(
                '/cortex.CortexCertification/GetContext',
                request_serializer=cortex__pb2.GetContextRequest.SerializeToString,
                response_deserializer=cortex__pb2.GetContextResponse.FromString,
                _registered_method=True)


class CortexCertificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Certify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexCertificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Certify': grpc.unary_unary_rpc_method_handler(
                    servicer.Certify,
                    request_deserializer=cortex__pb2.CertifyRequest.FromString,
                    response_serializer=cortex__pb2.CertifyResponse.SerializeToString,
            ),
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=cortex__pb2.GetContextRequest.FromString,
                    response_serializer=cortex__pb2.GetContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.CortexCertification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.CortexCertification', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CortexCertification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Certify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexCertification/Certify',
            cortex__pb2.CertifyRequest.SerializeToString,
            cortex__pb2.CertifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexCertification/GetContext',
            cortex__pb2.GetContextRequest.SerializeToString,
            cortex__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CortexMemoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/cortex.CortexMemory/Retrieve',
                request_serializer=cortex__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=cortex__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.Store = channel.unary_unary(
                '/cortex.CortexMemory/Store',
                request_serializer=cortex__pb2.StoreRequest.SerializeToString,
                response_deserializer=cortex__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/cortex.CortexMemory/Delete',
                request_serializer=cortex__pb2.DeleteRequest.SerializeToString,
                response_deserializer=cortex__pb2.DeleteResponse.FromString,
                _registered_method=True)


class CortexMemoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexMemoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=cortex__pb2.RetrieveRequest.FromString,
                    response_serializer=cortex__pb2.RetrieveResponse.SerializeToString,
            ),
            'Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Store,
                    request_deserializer=cortex__pb2.StoreRequest.FromString,
                    response_serializer=cortex__pb2.StoreResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=cortex__pb2.DeleteRequest.FromString,
                    response_serializer=cortex__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.CortexMemory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.CortexMemory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CortexMemory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexMemory/Retrieve',
            cortex__pb2.RetrieveRequest.SerializeToString,
            cortex__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexMemory/Store',
            cortex__pb2.StoreRequest.SerializeToString,
            cortex__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexMemory/Delete',
            cortex__pb2.DeleteRequest.SerializeToString,
            cortex__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CortexExperienceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordOutcome = channel.unary_unary(
                '/cortex.CortexExperience/RecordOutcome',
                request_serializer=cortex__pb2.RecordOutcomeRequest.SerializeToString,
                response_deserializer=cortex__pb2.RecordOutcomeResponse.FromString,
                _registered_method=True)
        self.GetOutcomeStats = channel.unary_unary(
                '/cortex.CortexExperience/GetOutcomeStats',
                request_serializer=cortex__pb2.OutcomeStatsRequest.SerializeToString,
                response_deserializer=cortex__pb2.OutcomeStatsResponse.FromString,
                _registered_method=True)


class CortexExperienceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutcomeStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexExperienceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordOutcome,
                    request_deserializer=cortex__pb2.RecordOutcomeRequest.FromString,
                    response_serializer=cortex__pb2.RecordOutcomeResponse.SerializeToString,
            ),
            'GetOutcomeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOutcomeStats,
                    request_deserializer=cortex__pb2.OutcomeStatsRequest.FromString,
                    response_serializer=cortex__pb2.OutcomeStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.CortexExperience', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.CortexExperience', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CortexExperience(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexExperience/RecordOutcome',
            cortex__pb2.RecordOutcomeRequest.SerializeToString,
            cortex__pb2.RecordOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutcomeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexExperience/GetOutcomeStats',
            cortex__pb2.OutcomeStatsRequest.SerializeToString,
            cortex__pb2.OutcomeStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CortexHealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/cortex.CortexHealth/Check',
                request_serializer=cortex__pb2.HealthRequest.SerializeToString,
                response_deserializer=cortex__pb2.HealthResponse.FromString,
                _registered_method=True)


class CortexHealthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexHealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=cortex__pb2.HealthRequest.FromString,
                    response_serializer=cortex__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.CortexHealth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.CortexHealth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CortexHealth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.CortexHealth/Check',
            cortex__pb2.HealthRequest.SerializeToString,
            cortex__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
