{{- if not .Values.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep   # don't delete secrets on helm uninstall
type: Opaque
stringData:
  {{- if .Values.security.apiKeys }}
  CORTEX_API_KEYS: {{ .Values.security.apiKeys | quote }}
  {{- end }}
  {{- if and .Values.externalRedis.enabled .Values.externalRedis.password }}
  CORTEX_REDIS_PASSWORD: {{ .Values.externalRedis.password | quote }}
  {{- end }}
{{- end }}
